# POST http://lasburgas.herokuapp.com/hamburguesa
# content-type: application/json

# {
#   "nombre": "borrar",
#   "precio": "4990",
#   "descripcion": "eso",
#   "imagen": "https://cdn.hswstatic.com/gif/cheeseburger-1.jpg"
# }

# GET http://lasburgas.herokuapp.com/hamburguesa

# DELETE http://lasburgas.herokuapp.com/hamburguesa/3

# PATCH  http://lasburgas.herokuapp.com/hamburguesa/1
# content-type: application/json

# {
#         "descripcion": "Mala burga"
# }

# POST http://localhost:3000/ingrediente
# content-type: application/json

# {
#         "name": "pepino",
#         "descripcion": "asd"
# }

# GET http://localhost:3000/ingrediente/2

# DELETE http://lasburgas.herokuapp.com/ingrediente/2

# PATCH  http://localhost:3000/ingrediente/5
# content-type: application/json

# {
#         "descripcion": "Mala"
# }


# PUT http://lasburgas.herokuapp.com/hamburguesa/2/ingrediente/3
# DELETE http://lasburgas.herokuapp.com/hamburguesa/2/ingrediente/2
